# Generated by Django 6.0.3 on 2026-03-20 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fcpl_rate', models.BooleanField(default=False)),
                ('pickup', models.BooleanField(default=False)),
                ('vendor_manage', models.BooleanField(default=False)),
                ('vendor_rates', models.BooleanField(default=False)),
                ('rate_update', models.BooleanField(default=False)),
                ('pincode', models.BooleanField(default=False)),
                ('user_management', models.BooleanField(default=False)),
                ('ba_b2b', models.BooleanField(default=False)),
            ],
        ),
    ]
