# Generated by Django 6.0.3 on 2026-04-07 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_customuser_created_at_customuser_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='create_order',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='shipment_details',
            field=models.BooleanField(default=False),
        ),
    ]
