# Generated by Django 6.0.3 on 2026-03-14 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pincode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pincode', models.CharField(max_length=6)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('is_oda', models.BooleanField(default=False)),
                ('zone', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'pincodes',
                'managed': False,
            },
        ),
    ]
