# Generated by Django 6.0.3 on 2026-03-15 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pincode', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_freight', models.DecimalField(decimal_places=2, default=600, max_digits=10)),
                ('docket_charge', models.DecimalField(decimal_places=2, default=50, max_digits=10)),
                ('fuel_percent', models.DecimalField(decimal_places=2, default=15, max_digits=5)),
                ('fov_charge', models.DecimalField(decimal_places=2, default=75, max_digits=10)),
                ('oda_per_kg', models.DecimalField(decimal_places=2, default=3, max_digits=10)),
                ('oda_min', models.DecimalField(decimal_places=2, default=650, max_digits=10)),
                ('cod_percent', models.DecimalField(decimal_places=2, default=0.25, max_digits=5)),
                ('cod_min', models.DecimalField(decimal_places=2, default=150, max_digits=10)),
                ('handling_100_400', models.DecimalField(decimal_places=2, default=2, max_digits=10)),
                ('handling_above_400', models.DecimalField(decimal_places=2, default=4, max_digits=10)),
                ('appointment_per_kg', models.DecimalField(decimal_places=2, default=4, max_digits=10)),
                ('appointment_min', models.DecimalField(decimal_places=2, default=1250, max_digits=10)),
                ('cft', models.DecimalField(decimal_places=2, default=4500, max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Global Charges',
                'verbose_name_plural': 'Global Charges',
                'db_table': 'charges',
            },
        ),
        migrations.AlterModelOptions(
            name='pincode',
            options={'managed': True, 'verbose_name': 'Pincode', 'verbose_name_plural': 'Pincodes'},
        ),
        migrations.CreateModel(
            name='RateMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_zone', models.CharField(max_length=5)),
                ('to_zone', models.CharField(max_length=5)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Rate Matrix',
                'verbose_name_plural': 'Rate Matrix',
                'unique_together': {('from_zone', 'to_zone')},
            },
        ),
    ]
