# Generated by Django 6.0.3 on 2026-03-15 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pincode', '0002_charges_alter_pincode_options_ratematrix'),
    ]

    operations = [
        migrations.AddField(
            model_name='pincode',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='pincode',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pincode',
            name='pincode',
            field=models.CharField(max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='pincode',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
