# Generated by Django 6.0.3 on 2026-03-06 15:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickup', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PickupRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_partner', models.CharField(max_length=100)),
                ('warehouse', models.CharField(max_length=100)),
                ('package_count', models.IntegerField()),
                ('pickup_date', models.DateField()),
                ('pickup_time', models.CharField(max_length=50)),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('assigned_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Pickup',
        ),
    ]
