# Generated by Django 6.0.3 on 2026-05-07 13:11

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickup', '0002_pickuprequest_delete_pickup'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pickuprequest',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='pickuprequest',
            name='assigned_user',
        ),
        migrations.RemoveField(
            model_name='pickuprequest',
            name='package_count',
        ),
        migrations.RemoveField(
            model_name='pickuprequest',
            name='shipping_partner',
        ),
        migrations.RemoveField(
            model_name='pickuprequest',
            name='warehouse',
        ),
        migrations.AddField(
            model_name='pickuprequest',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pickuprequest',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_pickups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pickuprequest',
            name='client',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='pickup_requests', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pickuprequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pickuprequest',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pickuprequest',
            name='delivery_address',
            field=models.TextField(default='Temporary'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pickuprequest',
            name='delivery_city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pickuprequest',
            name='delivery_name',
            field=models.CharField(default='Temp', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pickuprequest',
            name='delivery_phone',
            field=models.CharField(default='0000000000', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pickuprequest',
            name='delivery_pincode',
            field=models.CharField(default=1, max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pickuprequest',
            name='delivery_state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pickuprequest',
            name='material',
            field=models.CharField(choices=[('General Cargo', 'General Cargo'), ('Electronics', 'Electronics'), ('Furniture', 'Furniture'), ('Documents', 'Documents'), ('Automobile Parts', 'Automobile Parts'), ('Fragile Items', 'Fragile Items'), ('Perishable Goods', 'Perishable Goods'), ('Industrial Equipment', 'Industrial Equipment')], default='General Cargo', max_length=50),
        ),
        migrations.AddField(
            model_name='pickuprequest',
            name='packages',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='pickuprequest',
            name='picked_up_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pickuprequest',
            name='pickup_address',
            field=models.TextField(default=datetime.date(2026, 5, 7)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pickuprequest',
            name='pickup_city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pickuprequest',
            name='pickup_id',
            field=models.CharField(default=datetime.date(2026, 5, 7), editable=False, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pickuprequest',
            name='pickup_name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pickuprequest',
            name='pickup_phone',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pickuprequest',
            name='pickup_pincode',
            field=models.CharField(default='', max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pickuprequest',
            name='pickup_state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pickuprequest',
            name='preferred_time',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='pickuprequest',
            name='remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pickuprequest',
            name='special_instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pickuprequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='pickuprequest',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pickuprequest',
            name='pickup_time',
            field=models.CharField(choices=[('Morning', 'Morning (9AM - 12PM)'), ('Afternoon', 'Afternoon (12PM - 3PM)'), ('Evening', 'Evening (3PM - 6PM)'), ('Late Evening', 'Late Evening (6PM - 9PM)')], default='Morning', max_length=20),
        ),
        migrations.AlterField(
            model_name='pickuprequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ASSIGNED', 'Assigned'), ('PICKED_UP', 'Picked Up'), ('IN_TRANSIT', 'In Transit'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
        migrations.AlterModelTable(
            name='pickuprequest',
            table='pickup_requests',
        ),
        migrations.CreateModel(
            name='PickupAssignmentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_by_history', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_history', to=settings.AUTH_USER_MODEL)),
                ('pickup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_history', to='pickup.pickuprequest')),
            ],
            options={
                'db_table': 'pickup_assignment_history',
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='PickupNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('ASSIGNMENT', 'Pickup Assigned'), ('STATUS_UPDATE', 'Status Updated'), ('TASK', 'New Task'), ('TASK_COMPLETED', 'Task Completed'), ('REMINDER', 'Reminder')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pickup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='pickup.pickuprequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pickup_notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PickupTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('PAYMENT', 'Payment Collection'), ('DOCKET', 'Docket Clearance'), ('DELIVERY', 'Delivery Arrangement'), ('FOLLOWUP', 'Customer Follow-up'), ('POD', 'Proof of Delivery'), ('OTHER', 'Other Task')], default='OTHER', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('reply', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tasks', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_tasks', to=settings.AUTH_USER_MODEL)),
                ('pickup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='pickup.pickuprequest')),
            ],
            options={
                'db_table': 'pickup_tasks',
                'ordering': ['-created_at'],
            },
        ),
    ]
