# Generated by Django 6.0.3 on 2026-04-12 07:18

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('lr_number', models.BigIntegerField(default=200000)),
                ('awb_number', models.BigIntegerField(default=30000000)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'counters',
            },
        ),
        migrations.CreateModel(
            name='DashboardStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_shipments', models.IntegerField(default=0)),
                ('delivered_today', models.IntegerField(default=0)),
                ('in_transit', models.IntegerField(default=0)),
                ('pending_pickup', models.IntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Dashboard Stats',
                'db_table': 'dashboard_stats',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('pickup', 'Pickup'), ('delivery', 'Delivery')], max_length=10)),
                ('name', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('pincode', models.CharField(max_length=6)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('gstin', models.CharField(blank=True, max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'locations',
                'indexes': [models.Index(fields=['pincode'], name='locations_pincode_f65948_idx'), models.Index(fields=['type'], name='locations_type_f5c4b7_idx')],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lr_number', models.BigIntegerField(unique=True)),
                ('awb_number', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('pickup_name', models.CharField(max_length=200)),
                ('pickup_address', models.TextField()),
                ('pickup_pincode', models.CharField(max_length=6)),
                ('pickup_contact', models.CharField(max_length=15)),
                ('pickup_gstin', models.CharField(blank=True, max_length=20, null=True)),
                ('pickup_city', models.CharField(blank=True, max_length=100, null=True)),
                ('pickup_state', models.CharField(blank=True, max_length=100, null=True)),
                ('delivery_name', models.CharField(max_length=200)),
                ('delivery_address', models.TextField()),
                ('delivery_pincode', models.CharField(max_length=6)),
                ('delivery_contact', models.CharField(max_length=15)),
                ('delivery_gstin', models.CharField(blank=True, max_length=20, null=True)),
                ('delivery_city', models.CharField(blank=True, max_length=100, null=True)),
                ('delivery_state', models.CharField(blank=True, max_length=100, null=True)),
                ('material', models.CharField(default='General Cargo', max_length=200)),
                ('hsn_code', models.CharField(default='1234', max_length=20)),
                ('boxes', models.IntegerField(default=0)),
                ('weight', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('actual_weight', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('volumetric_weight', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('dimensions', models.JSONField(blank=True, default=list, help_text='List of box dimensions')),
                ('total_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('eway_bill', models.CharField(blank=True, max_length=20, null=True)),
                ('insurance_type', models.CharField(choices=[('owner', "Owner's Risk"), ('carrier', "Carrier's Risk"), ('none', 'No Insurance')], default='owner', max_length=20)),
                ('freight_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fuel_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('docket_charge', models.DecimalField(decimal_places=2, default=100, max_digits=10)),
                ('oda_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('gst', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('booked', '📝 Booked'), ('picked', '🚚 Picked Up'), ('in_transit', '🚛 In Transit'), ('out_for_delivery', '📦 Out for Delivery'), ('delivered', '✅ Delivered'), ('cancelled', '❌ Cancelled'), ('hold', '⏸️ On Hold'), ('dispatched', '✈️ Dispatched')], default='booked', max_length=20)),
                ('booking_mode', models.CharField(choices=[('surface', 'Surface Transport'), ('air', 'Air Express'), ('rail', 'Rail Cargo'), ('express', 'Speed Post')], default='surface', max_length=20)),
                ('current_location', models.CharField(blank=True, max_length=200, null=True)),
                ('tracking_history', models.JSONField(blank=True, default=list, help_text='List of status updates with timestamps')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expected_delivery_date', models.DateField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('delivery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_orders', to='shipments.location')),
                ('pickup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickup_orders', to='shipments.location')),
            ],
            options={
                'db_table': 'orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(max_length=50)),
                ('invoice_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('invoice_date', models.DateField(default=datetime.date.today)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='shipments.order')),
            ],
            options={
                'db_table': 'invoices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/%Y/%m/%d/')),
                ('doc_type', models.CharField(choices=[('invoice', 'Invoice'), ('eway', 'E-Way Bill'), ('pod', 'Proof of Delivery'), ('other', 'Other')], max_length=20)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('file_size', models.IntegerField(default=0, help_text='File size in bytes')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='shipments.order')),
            ],
            options={
                'db_table': 'documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='RateMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_zone', models.CharField(max_length=50)),
                ('to_zone', models.CharField(max_length=50)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('min_weight', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('max_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'rate_matrix',
                'unique_together': {('from_zone', 'to_zone')},
            },
        ),
        migrations.CreateModel(
            name='TrackingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_entries', to='shipments.order')),
            ],
            options={
                'db_table': 'tracking_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['lr_number'], name='orders_lr_numb_03c0ef_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['awb_number'], name='orders_awb_num_a29dd0_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='orders_status_762191_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['pickup_pincode'], name='orders_pickup__ec3f6e_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['delivery_pincode'], name='orders_deliver_f186af_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created_at'], name='orders_created_77e2b9_idx'),
        ),
    ]
