# Generated by Django 6.0.3 on 2026-04-07 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lr_number', models.BigIntegerField(default=200000)),
                ('awb_number', models.BigIntegerField(default=30000000)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('pickup', 'Pickup'), ('delivery', 'Delivery')], max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('pincode', models.CharField(max_length=6)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lr_number', models.BigIntegerField(unique=True)),
                ('awb_number', models.BigIntegerField()),
                ('pickup_name', models.CharField(max_length=100)),
                ('pickup_address', models.TextField()),
                ('pickup_pincode', models.CharField(max_length=10)),
                ('pickup_contact', models.CharField(max_length=15)),
                ('delivery_name', models.CharField(max_length=100)),
                ('delivery_address', models.TextField()),
                ('delivery_pincode', models.CharField(max_length=10)),
                ('delivery_contact', models.CharField(max_length=15)),
                ('material', models.CharField(max_length=100)),
                ('hsn_code', models.CharField(max_length=20)),
                ('boxes', models.IntegerField()),
                ('weight', models.FloatField()),
                ('total_value', models.FloatField()),
                ('eway_bill', models.CharField(blank=True, max_length=50, null=True)),
                ('insurance_type', models.CharField(choices=[('owner', 'Owner Risk'), ('carrier', 'Carrier Risk')], default='owner', max_length=20)),
                ('status', models.CharField(choices=[('booked', 'Booked'), ('in_transit', 'In Transit'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered')], default='booked', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivery', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_orders', to='shipments.location')),
                ('pickup', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickup_orders', to='shipments.location')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(max_length=50)),
                ('invoice_value', models.FloatField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='shipments.order')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/')),
                ('doc_type', models.CharField(choices=[('invoice', 'Invoice'), ('eway', 'E-Way'), ('other', 'Other')], max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='shipments.order')),
            ],
        ),
    ]
