# Generated by Django 6.0.3 on 2026-04-14 07:35

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Custom User', 'verbose_name_plural': 'Custom Users'},
        ),
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='ba_b2b',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='client_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='company',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='create_order',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 4, 14, 13, 5, 33, 260130)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_clients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customuser',
            name='fcpl_rate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='generate_invoice',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='gstin',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_client_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='pickup',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='pincode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='rate_update',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='shipment_details',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_management',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='vendor_manage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='vendor_rates',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='view_reports',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('User', 'User'), ('Client', 'Client')], default='User', max_length=10),
        ),
        migrations.AlterModelTable(
            name='customuser',
            table='accounts_custom_user',
        ),
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_type', models.CharField(blank=True, max_length=100, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('pan_number', models.CharField(blank=True, max_length=10, null=True)),
                ('registration_date', models.DateField(auto_now_add=True)),
                ('primary_contact_name', models.CharField(blank=True, max_length=100, null=True)),
                ('primary_contact_designation', models.CharField(blank=True, max_length=100, null=True)),
                ('secondary_contact_name', models.CharField(blank=True, max_length=100, null=True)),
                ('secondary_contact_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('preferred_payment_mode', models.CharField(blank=True, max_length=20, null=True)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('current_credit_used', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_orders', models.IntegerField(default=0)),
                ('total_shipments', models.IntegerField(default=0)),
                ('total_freight', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('last_order_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_client_profile',
            },
        ),
        migrations.CreateModel(
            name='ClientRatePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surface_rate_per_kg', models.DecimalField(decimal_places=2, default=18, max_digits=10)),
                ('express_rate_per_kg', models.DecimalField(decimal_places=2, default=25, max_digits=10)),
                ('air_rate_per_kg', models.DecimalField(decimal_places=2, default=45, max_digits=10)),
                ('rail_rate_per_kg', models.DecimalField(decimal_places=2, default=15, max_digits=10)),
                ('min_freight', models.DecimalField(decimal_places=2, default=650, max_digits=10)),
                ('docket_charge', models.DecimalField(decimal_places=2, default=100, max_digits=10)),
                ('fuel_percent', models.DecimalField(decimal_places=2, default=10, max_digits=5)),
                ('fov_charge', models.DecimalField(decimal_places=2, default=75, max_digits=10)),
                ('oda_charge', models.DecimalField(decimal_places=2, default=3, max_digits=10)),
                ('cod_charge', models.DecimalField(decimal_places=2, default=150, max_digits=10)),
                ('cod_percent', models.DecimalField(decimal_places=2, default=2.5, max_digits=5)),
                ('fragile_charge', models.DecimalField(decimal_places=2, default=250, max_digits=10)),
                ('appointment_charge', models.DecimalField(decimal_places=2, default=1500, max_digits=10)),
                ('handling_charge', models.DecimalField(decimal_places=2, default=2, max_digits=10)),
                ('insurance_percent', models.DecimalField(decimal_places=2, default=2, max_digits=5)),
                ('express_extra', models.DecimalField(decimal_places=2, default=5, max_digits=10)),
                ('gst_percent', models.DecimalField(decimal_places=2, default=18, max_digits=5)),
                ('cft', models.DecimalField(decimal_places=2, default=4500, max_digits=10)),
                ('is_custom', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rate_policy', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_policies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_client_rate_policy',
            },
        ),
        migrations.CreateModel(
            name='ClientSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=500, unique=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('login_time', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_client_session',
            },
        ),
        migrations.CreateModel(
            name='ClientOrderSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('total_orders', models.IntegerField(default=0)),
                ('total_shipments', models.IntegerField(default=0)),
                ('total_freight', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_invoice_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_summaries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_client_order_summary',
                'ordering': ['-year', '-month'],
                'unique_together': {('client', 'year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='ClientRateMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_zone', models.CharField(choices=[('N1', 'North Zone 1'), ('N2', 'North Zone 2'), ('N3', 'North Zone 3'), ('C1', 'Central Zone 1'), ('W1', 'West Zone 1'), ('W2', 'West Zone 2'), ('S1', 'South Zone 1'), ('S2', 'South Zone 2'), ('E1', 'East Zone 1'), ('NE1', 'North East 1'), ('NE2', 'North East 2')], max_length=5)),
                ('to_zone', models.CharField(choices=[('N1', 'North Zone 1'), ('N2', 'North Zone 2'), ('N3', 'North Zone 3'), ('C1', 'Central Zone 1'), ('W1', 'West Zone 1'), ('W2', 'West Zone 2'), ('S1', 'South Zone 1'), ('S2', 'South Zone 2'), ('E1', 'East Zone 1'), ('NE1', 'North East 1'), ('NE2', 'North East 2')], max_length=5)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('surface_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('express_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('air_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rail_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_matrix', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_rates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_client_rate_matrix',
                'ordering': ['from_zone', 'to_zone'],
                'unique_together': {('client', 'from_zone', 'to_zone')},
            },
        ),
    ]
