# Generated by Django 6.0.3 on 2026-03-20 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendors', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_type', models.CharField(choices=[('fcpl', 'FCPL'), ('b2b', 'BA & B2B')], max_length=10)),
                ('zone', models.CharField(max_length=50)),
                ('payment_mode', models.CharField(choices=[('Prepaid', 'Prepaid'), ('COD', 'COD')], max_length=20)),
                ('per_kg_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('docket_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fuel_charge', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('oda_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('insurance_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('appointment_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('weight_min', models.IntegerField(default=0)),
                ('weight_max', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendors.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='RateMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_zone', models.CharField(max_length=5)),
                ('to_zone', models.CharField(max_length=5)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Rate Matrix',
                'verbose_name_plural': 'Rate Matrix',
                'unique_together': {('from_zone', 'to_zone')},
            },
        ),
    ]
