# Generated by Django 6.0.3 on 2026-03-08 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(max_length=50)),
                ('payment_mode', models.CharField(choices=[('Prepaid', 'Prepaid'), ('COD', 'COD')], max_length=20)),
                ('per_kg_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('oda_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('insurance_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('appointment_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('weight_min', models.IntegerField(default=0)),
                ('weight_max', models.IntegerField(default=0)),
            ],
        ),
    ]
