# Generated by Django 6.0.3 on 2026-03-14 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0002_ratecard'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratecard',
            name='docket_charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ratecard',
            name='fuel_charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='ratecard',
            name='rate_type',
            field=models.CharField(choices=[('fcpl', 'FCPL'), ('b2b', 'BA & B2B')], default='Unknown', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ratecard',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
