# Generated by Django 6.0.3 on 2026-03-14 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0003_ratecard_docket_charge_ratecard_fuel_charge_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_zone', models.CharField(max_length=5)),
                ('to_zone', models.CharField(max_length=5)),
                ('rate', models.FloatField()),
            ],
        ),
    ]
