# Generated by Django 6.0.3 on 2026-03-14 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0004_ratematrix'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ratematrix',
            options={'verbose_name': 'Rate Matrix', 'verbose_name_plural': 'Rate Matrix'},
        ),
        migrations.AddField(
            model_name='ratematrix',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='ratematrix',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterUniqueTogether(
            name='ratematrix',
            unique_together={('from_zone', 'to_zone')},
        ),
    ]
