# Generated by Django 6.0.3 on 2026-03-18 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0005_alter_ratematrix_options_ratematrix_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratematrix',
            name='updated_at',
        ),
    ]
