# Generated by Django 6.0.3 on 2026-03-30 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0006_remove_ratematrix_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratecard',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
