# Generated by Django 6.0.3 on 2026-04-14 07:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0007_alter_ratecard_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ratematrix',
            name='air_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='ratematrix',
            name='express_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='ratematrix',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ratematrix',
            name='rail_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='ratematrix',
            name='surface_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='ratematrix',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='ratematrix',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ratematrix',
            name='from_zone',
            field=models.CharField(choices=[('N1', 'North Zone 1'), ('N2', 'North Zone 2'), ('N3', 'North Zone 3'), ('C1', 'Central Zone 1'), ('W1', 'West Zone 1'), ('W2', 'West Zone 2'), ('S1', 'South Zone 1'), ('S2', 'South Zone 2'), ('E1', 'East Zone 1'), ('NE1', 'North East 1'), ('NE2', 'North East 2')], max_length=5),
        ),
        migrations.AlterField(
            model_name='ratematrix',
            name='to_zone',
            field=models.CharField(choices=[('N1', 'North Zone 1'), ('N2', 'North Zone 2'), ('N3', 'North Zone 3'), ('C1', 'Central Zone 1'), ('W1', 'West Zone 1'), ('W2', 'West Zone 2'), ('S1', 'South Zone 1'), ('S2', 'South Zone 2'), ('E1', 'East Zone 1'), ('NE1', 'North East 1'), ('NE2', 'North East 2')], max_length=5),
        ),
        migrations.AlterModelTable(
            name='ratecard',
            table='rates_rate_card',
        ),
        migrations.AlterModelTable(
            name='ratematrix',
            table='rates_rate_matrix',
        ),
        migrations.CreateModel(
            name='ClientRatePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surface_rate_per_kg', models.DecimalField(decimal_places=2, default=18, max_digits=10)),
                ('express_rate_per_kg', models.DecimalField(decimal_places=2, default=25, max_digits=10)),
                ('air_rate_per_kg', models.DecimalField(decimal_places=2, default=45, max_digits=10)),
                ('rail_rate_per_kg', models.DecimalField(decimal_places=2, default=15, max_digits=10)),
                ('min_freight', models.DecimalField(decimal_places=2, default=650, max_digits=10)),
                ('docket_charge', models.DecimalField(decimal_places=2, default=100, max_digits=10)),
                ('fuel_percent', models.DecimalField(decimal_places=2, default=10, max_digits=5)),
                ('fov_charge', models.DecimalField(decimal_places=2, default=75, max_digits=10)),
                ('oda_charge', models.DecimalField(decimal_places=2, default=3, max_digits=10)),
                ('cod_charge', models.DecimalField(decimal_places=2, default=150, max_digits=10)),
                ('cod_percent', models.DecimalField(decimal_places=2, default=2.5, max_digits=5)),
                ('fragile_charge', models.DecimalField(decimal_places=2, default=250, max_digits=10)),
                ('appointment_charge', models.DecimalField(decimal_places=2, default=1500, max_digits=10)),
                ('handling_charge', models.DecimalField(decimal_places=2, default=2, max_digits=10)),
                ('insurance_percent', models.DecimalField(decimal_places=2, default=2, max_digits=5)),
                ('express_extra', models.DecimalField(decimal_places=2, default=5, max_digits=10)),
                ('gst_percent', models.DecimalField(decimal_places=2, default=18, max_digits=5)),
                ('cft', models.DecimalField(decimal_places=2, default=4500, max_digits=10)),
                ('is_custom', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.OneToOneField(limit_choices_to={'role': 'Client'}, on_delete=django.db.models.deletion.CASCADE, related_name='custom_rate_policy', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_client_policies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rates_client_rate_policy',
            },
        ),
        migrations.CreateModel(
            name='MasterRatePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surface_rate_per_kg', models.DecimalField(decimal_places=2, default=18, max_digits=10)),
                ('express_rate_per_kg', models.DecimalField(decimal_places=2, default=25, max_digits=10)),
                ('air_rate_per_kg', models.DecimalField(decimal_places=2, default=45, max_digits=10)),
                ('rail_rate_per_kg', models.DecimalField(decimal_places=2, default=15, max_digits=10)),
                ('min_freight', models.DecimalField(decimal_places=2, default=650, max_digits=10)),
                ('docket_charge', models.DecimalField(decimal_places=2, default=100, max_digits=10)),
                ('fuel_percent', models.DecimalField(decimal_places=2, default=10, max_digits=5)),
                ('fov_charge', models.DecimalField(decimal_places=2, default=75, max_digits=10)),
                ('oda_charge', models.DecimalField(decimal_places=2, default=3, max_digits=10)),
                ('cod_charge', models.DecimalField(decimal_places=2, default=150, max_digits=10)),
                ('cod_percent', models.DecimalField(decimal_places=2, default=2.5, max_digits=5)),
                ('fragile_charge', models.DecimalField(decimal_places=2, default=250, max_digits=10)),
                ('appointment_charge', models.DecimalField(decimal_places=2, default=1500, max_digits=10)),
                ('handling_charge', models.DecimalField(decimal_places=2, default=2, max_digits=10)),
                ('insurance_percent', models.DecimalField(decimal_places=2, default=2, max_digits=5)),
                ('express_extra', models.DecimalField(decimal_places=2, default=5, max_digits=10)),
                ('gst_percent', models.DecimalField(decimal_places=2, default=18, max_digits=5)),
                ('cft', models.DecimalField(decimal_places=2, default=4500, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rates_master_rate_policy',
            },
        ),
        migrations.CreateModel(
            name='ClientRateMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_zone', models.CharField(choices=[('N1', 'North Zone 1'), ('N2', 'North Zone 2'), ('N3', 'North Zone 3'), ('C1', 'Central Zone 1'), ('W1', 'West Zone 1'), ('W2', 'West Zone 2'), ('S1', 'South Zone 1'), ('S2', 'South Zone 2'), ('E1', 'East Zone 1'), ('NE1', 'North East 1'), ('NE2', 'North East 2')], max_length=5)),
                ('to_zone', models.CharField(choices=[('N1', 'North Zone 1'), ('N2', 'North Zone 2'), ('N3', 'North Zone 3'), ('C1', 'Central Zone 1'), ('W1', 'West Zone 1'), ('W2', 'West Zone 2'), ('S1', 'South Zone 1'), ('S2', 'South Zone 2'), ('E1', 'East Zone 1'), ('NE1', 'North East 1'), ('NE2', 'North East 2')], max_length=5)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('surface_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('express_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('air_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rail_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(limit_choices_to={'role': 'Client'}, on_delete=django.db.models.deletion.CASCADE, related_name='custom_rate_matrix', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_client_rates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rates_client_rate_matrix',
                'ordering': ['from_zone', 'to_zone'],
                'unique_together': {('client', 'from_zone', 'to_zone')},
            },
        ),
    ]
