# Generated by Django 6.0.3 on 2026-03-14 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='created_at',
        ),
        migrations.AddField(
            model_name='vendor',
            name='contact',
            field=models.CharField(default='Unknown', max_length=20),
            preserve_default=False,
        ),
    ]
