# Generated by Django 6.0.3 on 2026-03-18 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_remove_vendor_created_at_vendor_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='vendorrate',
            name='docket_charge',
        ),
        migrations.RemoveField(
            model_name='vendorrate',
            name='fuel_charge',
        ),
        migrations.RemoveField(
            model_name='vendorrate',
            name='min_weight',
        ),
        migrations.RemoveField(
            model_name='vendorrate',
            name='oda_charge',
        ),
        migrations.RemoveField(
            model_name='vendorrate',
            name='rate',
        ),
        migrations.RemoveField(
            model_name='vendorrate',
            name='vendor',
        ),
        migrations.RemoveField(
            model_name='vendorrate',
            name='zone',
        ),
        migrations.AddField(
            model_name='vendor',
            name='contact_person',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='gstin',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vendorrate',
            name='charges',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='vendorrate',
            name='rates',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='vendorrate',
            name='vendor_name',
            field=models.CharField(default='NA', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vendor',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
