# Generated by Django 6.0.3 on 2026-04-26 06:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0003_remove_vendor_contact_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZoneMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_code', models.CharField(choices=[('N1', 'North Zone 1'), ('N2', 'North Zone 2'), ('N3', 'North Zone 3'), ('C1', 'Central Zone 1'), ('W1', 'West Zone 1'), ('W2', 'West Zone 2'), ('S1', 'South Zone 1'), ('S2', 'South Zone 2'), ('E1', 'East Zone 1'), ('NE1', 'North East Zone 1'), ('NE2', 'North East Zone 2'), ('NE3', 'North East Zone 3')], max_length=10, unique=True)),
                ('zone_name', models.CharField(max_length=100)),
                ('pincodes', models.JSONField(default=list, help_text='List of pincodes in this zone')),
                ('state_codes', models.JSONField(blank=True, default=list, help_text='List of state codes')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Zone Master',
                'verbose_name_plural': 'Zone Masters',
                'db_table': 'zone_master',
                'ordering': ['zone_code'],
            },
        ),
        migrations.AlterModelOptions(
            name='vendor',
            options={'ordering': ['name'], 'verbose_name': 'Vendor', 'verbose_name_plural': 'Vendors'},
        ),
        migrations.AlterModelOptions(
            name='vendorrate',
            options={'ordering': ['vendor_name'], 'verbose_name': 'Vendor Rate', 'verbose_name_plural': 'Vendor Rates'},
        ),
        migrations.RenameField(
            model_name='vendor',
            old_name='location',
            new_name='city',
        ),
        migrations.AddField(
            model_name='vendor',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='alternate_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendor',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='pan',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='pincode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='serviceable_pincodes',
            field=models.JSONField(blank=True, default=list, help_text='List of serviceable pincodes'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='vendor_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='vendor_type',
            field=models.CharField(choices=[('surface', 'Surface Transport'), ('air', 'Air Cargo'), ('express', 'Express Delivery'), ('rail', 'Rail Cargo'), ('all', 'All Services')], default='surface', max_length=20),
        ),
        migrations.AddField(
            model_name='vendorrate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendorrate',
            name='delhivery_10cft',
            field=models.JSONField(blank=True, default=dict, help_text='10 CFT rates for Delhivery - Format: {from_zone: {to_zone: rate}}'),
        ),
        migrations.AddField(
            model_name='vendorrate',
            name='delhivery_6cft',
            field=models.JSONField(blank=True, default=dict, help_text='6 CFT rates for Delhivery - Format: {from_zone: {to_zone: rate}}'),
        ),
        migrations.AddField(
            model_name='vendorrate',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vendorrate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='vendorrate',
            name='updated_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vendorrate',
            name='charges',
            field=models.JSONField(default=dict, help_text='Additional charges like docket, FSC, GST, FOV, minimum freight etc.'),
        ),
        migrations.AlterField(
            model_name='vendorrate',
            name='rates',
            field=models.JSONField(default=dict, help_text='Zone to zone rate matrix - Format: {from_zone: {to_zone: rate}}'),
        ),
        migrations.AlterField(
            model_name='vendorrate',
            name='vendor_name',
            field=models.CharField(choices=[('DELHIVERY', 'Delhivery'), ('GATI', 'Gati'), ('PD', 'PD Logistics'), ('RIVIGO', 'Rivigo'), ('VXPRESS', 'V-Express'), ('FCPL', 'Faith Cargo'), ('XPRESSBEES', 'XpressBees')], help_text='Name of the logistics vendor', max_length=100, unique=True),
        ),
        migrations.AlterModelTable(
            name='vendor',
            table='vendors',
        ),
        migrations.AlterModelTable(
            name='vendorrate',
            table='vendor_rates',
        ),
        migrations.CreateModel(
            name='B2BRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_zone', models.CharField(max_length=50)),
                ('to_zone', models.CharField(max_length=50)),
                ('rate_per_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('mode', models.CharField(choices=[('surface', 'Surface Transport'), ('air', 'Air Cargo'), ('express', 'Express Delivery'), ('rail', 'Rail Cargo')], default='surface', max_length=20)),
                ('min_freight', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'B2B Rate',
                'verbose_name_plural': 'B2B Rates',
                'db_table': 'b2b_rates',
                'ordering': ['from_zone', 'to_zone'],
                'unique_together': {('from_zone', 'to_zone', 'mode')},
            },
        ),
        migrations.CreateModel(
            name='RateHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_rates', models.JSONField(default=dict)),
                ('new_rates', models.JSONField(default=dict)),
                ('old_charges', models.JSONField(blank=True, default=dict)),
                ('new_charges', models.JSONField(blank=True, default=dict)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='vendors.vendorrate')),
            ],
            options={
                'verbose_name': 'Rate History',
                'verbose_name_plural': 'Rate Histories',
                'db_table': 'rate_history',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='VendorServiceRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('surface', 'Surface'), ('air', 'Air Cargo'), ('express', 'Express'), ('rail', 'Rail Cargo'), ('cft_6', '6 CFT (Delhivery)'), ('cft_10', '10 CFT (Delhivery)')], max_length=20)),
                ('rates', models.JSONField(default=dict, help_text='Zone to zone rates for this service')),
                ('min_weight', models.FloatField(default=0, help_text='Minimum weight for this service')),
                ('max_weight', models.FloatField(blank=True, default=0, help_text='Maximum weight for this service', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_rates', to='vendors.vendorrate')),
            ],
            options={
                'verbose_name': 'Vendor Service Rate',
                'verbose_name_plural': 'Vendor Service Rates',
                'db_table': 'vendor_service_rates',
                'unique_together': {('vendor', 'service_type')},
            },
        ),
    ]
