# Generated by Django 6.0.3 on 2026-04-26 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0004_zonemaster_alter_vendor_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorPincode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pincode', models.CharField(max_length=10)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('is_oda', models.BooleanField(default=False)),
                ('oda_charge_per_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('oda_min_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_serviceable', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pincodes', to='vendors.vendorrate')),
            ],
            options={
                'verbose_name': 'Vendor Pincode',
                'verbose_name_plural': 'Vendor Pincodes',
                'db_table': 'vendor_pincodes',
                'ordering': ['vendor__vendor_name', 'pincode'],
                'unique_together': {('vendor', 'pincode')},
            },
        ),
    ]
