# Generated by Django 6.0.3 on 2026-04-26 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0005_vendorpincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorpincode',
            name='oda_category',
            field=models.CharField(blank=True, choices=[('A', 'ODA A - ₹2/kg (Min ₹200)'), ('B', 'ODA B - ₹4/kg (Min ₹400)'), ('C', 'ODA C - ₹7/kg (Min ₹700)'), ('D', 'ODA D - ₹10/kg (Min ₹1000)'), ('NONE', 'Non-ODA')], default='NONE', help_text='ODA Category: A, B, C, or D', max_length=10),
        ),
    ]
