# Generated by Django 6.0.3 on 2026-04-26 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0006_vendorpincode_oda_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorpincode',
            name='is_oda',
            field=models.BooleanField(db_index=True, default=False, help_text='Is this pincode Out of Delivery Area?'),
        ),
        migrations.AlterField(
            model_name='vendorpincode',
            name='is_serviceable',
            field=models.BooleanField(default=True, help_text='Is this pincode serviceable by the vendor?'),
        ),
        migrations.AlterField(
            model_name='vendorpincode',
            name='oda_charge_per_kg',
            field=models.DecimalField(decimal_places=2, default=0, help_text='ODA charge per kg', max_digits=10),
        ),
        migrations.AlterField(
            model_name='vendorpincode',
            name='oda_min_charge',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Minimum ODA charge', max_digits=10),
        ),
        migrations.AlterField(
            model_name='vendorpincode',
            name='pincode',
            field=models.CharField(db_index=True, help_text='6-digit pincode', max_length=20),
        ),
        migrations.AlterField(
            model_name='vendorrate',
            name='vendor_name',
            field=models.CharField(choices=[('DELHIVERY', 'Delhivery'), ('GATI', 'Gati'), ('PD LOGISTICS', 'PD Logistics'), ('RIVIGO', 'Rivigo'), ('VXPRESS', 'V-Express'), ('FCPL', 'Faith Cargo'), ('XPRESSBEES', 'XpressBees')], help_text='Name of the logistics vendor', max_length=100, unique=True),
        ),
        migrations.AddIndex(
            model_name='vendorpincode',
            index=models.Index(fields=['vendor', 'pincode'], name='vendor_pinc_vendor__8a0a64_idx'),
        ),
        migrations.AddIndex(
            model_name='vendorpincode',
            index=models.Index(fields=['is_oda'], name='vendor_pinc_is_oda_0f4044_idx'),
        ),
        migrations.AddIndex(
            model_name='vendorpincode',
            index=models.Index(fields=['oda_category'], name='vendor_pinc_oda_cat_7c3e31_idx'),
        ),
    ]
