# Generated by Django 6.0.3 on 2026-04-27 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0007_alter_vendorpincode_is_oda_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkUploadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_type', models.CharField(choices=[('pincode', 'Pincode Upload'), ('rate', 'Rate Upload'), ('vendor', 'Vendor Upload')], max_length=20)),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('total_records', models.IntegerField(default=0)),
                ('success_records', models.IntegerField(default=0)),
                ('failed_records', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('uploaded_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Bulk Upload Log',
                'verbose_name_plural': 'Bulk Upload Logs',
                'db_table': 'bulk_upload_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='vendorpincode',
            index=models.Index(fields=['pincode'], name='vendor_pinc_pincode_bc7db1_idx'),
        ),
        migrations.AddIndex(
            model_name='vendorservicerate',
            index=models.Index(fields=['vendor', 'service_type'], name='vendor_serv_vendor__2205bf_idx'),
        ),
        migrations.AddIndex(
            model_name='vendorservicerate',
            index=models.Index(fields=['is_active'], name='vendor_serv_is_acti_325284_idx'),
        ),
        migrations.AddField(
            model_name='bulkuploadlog',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vendors.vendorrate'),
        ),
    ]
